### PR TITLE
Update tinfoilshop.json

### PR DESCRIPTION
**Pull request by VoXaN24**
New address of my shop (the old work too but new is better :D)

### CODE REVIEW

**Comment by carcaschoi** [comment]
Thank you！

**Comment by carcaschoi** [comment]
Would you like to update your discord link？

**Comment by VoXaN24** [comment]
The Discord link is Up To date so it's ok 😄

**Comment by carcaschoi** [comment]
I see. It is my fault😅. Thank you for your awesome tinfoil shop

**Pull request merged**
